FROM node:20.17.0-bullseye-slim

WORKDIR /usr/src/app

COPY package*.json ./

# Install build dependencies and rebuild bcrypt
RUN apt-get update && apt-get install -y python3 make g++
RUN npm install
RUN npm rebuild bcrypt --build-from-source

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:dev"]