name: fighter-api-app
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - node_modules:/usr/src/app/node_modules
      - sessions:/usr/src/app/sessions
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  node_modules:
  sessions:

networks:
  app-network:
    name: fighter-network
    driver: bridge
    external: true